package net.mitrol.focus.supervisor.common.enums;

/**
 * Widget types
 * @author ladassus
 */
public enum WidgetType {
    INTERACTION_STATES("INTERACTION_STATES"),
    AGENT_STATES("AGENT_STATES"),
    INTERACTIONS_COUNTER("INTERACTIONS_COUNTER"),
    STATES_TIME_COUNTER("STATES_TIME_COUNTER"),
    AUXILIARY_STATES("AUXILIARY_STATES"),
    INTERACTIONS_DETAILS_COUNTER("INTERACTIONS_DETAILS_COUNTER"),
    AUXILIARY_STATES_TIME_COUNTER("AUXILIARY_STATES_TIME_COUNTER"),
    DISPOSITIONS_COUNTER("DISPOSITIONS_COUNTER"),
    SKILL_INDICATORS("SKILL_INDICATORS"),
    AGENT_INTERACTION_STATES("AGENT_INTERACTION_STATES"),
    SKILL_INTERACTIONS_COUNTER("SKILL_INTERACTIONS_COUNTER"),
    AGENT_INTERACTIONS_COUNTER("AGENT_INTERACTIONS_COUNTER"),
    AGENT_INFORMATION("AGENT_INFORMATION");

    private String name;

    WidgetType(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
