package net.mitrol.focus.supervisor.common.enums;

/**
 * Widget types
 * @author ladassus
 */
public enum WidgetType {
    INTERACTION_STATES,
    AGENT_STATES,
    INTERACTIONS_COUNTER,
    STATES_TIME_COUNTER,
    AUXILIARY_STATES,
    INTERACTIONS_DETAILS_COUNTER,
    AUXILIARY_STATES_TIME_COUNTER,
    DISPOSITIONS_COUNTER,
    SKILL_INDICATORS,
    AGENT_INTERACTION_STATES,
    SKILL_INTERACTIONS_COUNTER,
    AGENT_INTERACTIONS_COUNTER,
    AGENT_INFORMATION
}
